server:
  port: 8080

spring:
  application:
    name: webClient

management:
  endpoint:
    health:
      show-details: always # never or when-authorized
  endpoints:
    web:
      exposure:
        include: metrics,prometheus