server:
  port: 8765

spring:
  profiles:
    include:
      - eclient
  cloud:
    gateway:
      discovery:
        locator:
          # позволяет не соблюдать регистр при обращении к сервисам
          lower-case-service-id: true
      routes:
        - id: storage
          # lb - балансировщик нагрузки, для обращения к сервису нужно его имя
          uri: lb://productStorage # spring.application.name
          predicates:
            - Path=/storage/**,/kitchen/**
        - id: personnel
          uri: lb://personnel
          predicates:
            - Path=/personnel/**
