server:
  port: 8082

spring:
  profiles:
    include: # Unconditionally activate profiles (yaml)
      - eclient # eureka defaultZone
#    active: # List of active profiles
#      - test
#    default: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"