# Доп настройки приложения personnel-service для профиля prod
spring:
  datasource: # контейнер postgresql не настроен
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurantapi
    username: root
    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
