server:
  port: 8080

spring:
  profiles:
    include:
      - eclient

management:
  endpoint:
    health:
      show-details: always # never or when-authorized
  endpoints:
    web:
      exposure:
        include: metrics,prometheus

# Для подключения через RestClient к api-gateway
gateway:
  uri: http://localhost:8765

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"