# Настройки приложения web-client
server:
  port: 8080

spring:
  profiles:
    include:
      - eclient

# Для подключения через RestClient к api-gateway
gateway:
  uri: http://localhost:8765

management:
  endpoint:
    health:
      show-details: always # never or when-authorized
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
