server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/Developer/Terminal/JavaSpringProjects/api-configs
#          uri: file://${user.home}/Desktop/Developer/Terminal/JavaSpringProjects/api-configs
#          uri: file://C:/Users/<name>/Desktop/Developer/Terminal/JavaSpringProjects/api-configs
          defaultLabel: master